### ISSUE TITLE
Ramses 0.5.0

### ISSUE THREAD

**Issue by adam-codeberg** [brandicted/ramses-example#53]
Wanted to test the example due to missing Model errors I was getting with nested elements in the RAML file.
However ended up with this error http://pastebin.com/j0T7JcTQ under Ramses 0.5.0 with Pyton 2.7

**Comment by jstoiko** [comment]
If I had to take a guess, you may be using the RAML file of Ramses-example without it's _init_ file, could that be?

It's complaining that you're missing this function: https://github.com/brandicted/ramses-example/blob/master/ramses_example/__init__.py#L35

**Comment by adam-codeberg** [comment]
Think you're right, thanks for that!
