### ISSUE TITLE
securitySchemes: "allow admin all" vs allow g:admin all

### ISSUE THREAD

**Issue by adam-codeberg** [brandicted/ramses-example#55]
Trying to determine which is the correct securitySchemes syntax with the current version of ramses.
- allow admin all
- allow g:admin all

Also, is the below function and register method still valid?

``` Python
def my_is_admin(cls, user):
    """ Example of overriding """
    log.info('Checking if user {} is admin'.format(user))
    return 'admin' in user.groups
registry.add('User.is_admin', classmethod(my_is_admin))
```

I'm having trouble authenticating with the admin group.

**Comment by adam-codeberg** [comment]
Resolved the issue. Was my mistake.

Overlooked that the user.groups field needs to be list fieldtype.

I failed to do that and it was causing problems when the standard is_admin method was being run.

**Comment by jstoiko** [comment]
Kk
